### ISSUE TITLE
Camera device report ERROR

### ISSUE THREAD

**Issue by wohehehe** [aixxe/2dxcamhook#1]
Hi, should I do some special setting in OBS?
I set both my camera and virtual camera a spout 2 fliter, and rename them as Camera A and Camera B,
Then I use spice2x with -k 2dxcambook.dll to boot LDJ
But it looks like totally not work, camera device just report error.

**Comment by aixxe** [comment]
Make sure you are also booting with the `-iidxdisablecams` option. As counter-intuitive as this sounds, it will ensure the game initialises the dummy camera devices instead of trying to use any real hardware during boot.

If that gets you past the boot error, but still doesn't show anything in-game, ensure the library loaded correctly in `log.txt`:
```
[2023/11/17 09:51:42] I:launcher: loading hook DLL ..\addons\2dxcamhook.dll
[2023/11/17 09:51:42] I:libraryhook: LibraryHook Attach
```
This assumes you renamed the downloaded file. If you didn't, either rename it to `2dxcamhook.dll` or use the full filename.

If there is a failed line after this, you are most likely missing a dependency. Try dragging the `2dxcamhook.dll` file into something like [Dependencies](https://github.com/lucasg/Dependencies) to narrow it down. It's usually always the [Visual C++ runtime](https://aka.ms/vs/17/release/vc_redist.x64.exe) though.

**Comment by wohehehe** [comment]
It works, thank you!
